# i3config-rust v0.3

[icons]
icons = "awesome"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %R "

[[block]]
block = "battery"
interval = 60 # seconds
format = " $icon $percentage " 
if_command = "test -e /sys/class/power_supply/BAT0"
missing_format = ""

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "sound"
device_kind = "sink"
show_volume_when_muted = true

[[block]]
block = "sound"
device_kind = "source"
show_volume_when_muted = true

